import asyncio
import threading
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from mimetypes import guess_type
from aiosmtplib import SMTP
from datetime import datetime
import os
from psycopg2 import Error
from db_utils import get_connection, has_internet


SMTP_CONFIG = {
    "host": "smtp.gmail.com",
    "port": 587,
    "user": "citadel.project00@gmail.com",
    "password": "ljcx sgug xwob grtw",
    "tls": True
}


UCC_LOGO_WIDTH = 100
UCC_LOGO_HEIGHT = 100
LOGO_WIDTH = 120
LOGO_HEIGHT = 120


def format_datetime(dt_string: str) -> tuple:
    try:
        dt = datetime.strptime(dt_string, "%Y-%m-%d %H:%M:%S")
        date = dt.strftime("%B %d, %Y")
        time = dt.strftime("%I:%M %p").lstrip("0")
        return date, time
    except Exception:
        parts = dt_string.split()
        return parts[0], parts[1] if len(parts) > 1 else ""


def find_image(image_paths: list) -> str:
    for path in image_paths:
        if os.path.exists(path):
            return path
    return None


async def send_campus_notification(guardian_email: str, student_name: str, timestamp: str, notification_type: str = "entry"):
    formatted_date, formatted_time = format_datetime(timestamp)
    script_dir = os.path.dirname(os.path.abspath(__file__))

    logo_path = find_image([
        os.path.join(script_dir, "logo.png"),
        os.path.join(script_dir, "/gui/assets/logo.png"),
        "C:/Citadel/gui/assets/logo.png"
    ])
    ucc_logo_path = find_image([
        os.path.join(script_dir, "ucc.png"),
        os.path.join(script_dir, "./gui/assets/ucc.png"),
        "C:/Citadel/gui/assets/ucc.png"
    ])

    is_entry = notification_type.lower() == "entry"
    action_text = "entered" if is_entry else "exited"
    notification_title = "Campus Entry Notification" if is_entry else "Campus Exit Notification"
    subject_text = "Entry" if is_entry else "Exit"

    msg = MIMEMultipart("related")
    msg["From"] = SMTP_CONFIG["user"]
    msg["To"] = guardian_email
    msg["Subject"] = f"Campus {subject_text} Notification - {student_name}"

    alt = MIMEMultipart("alternative")
    msg.attach(alt)

    plain = f"""{notification_title}

Dear Parent/Guardian,

This is to inform you that your child, {student_name}, has {action_text} the University of Caloocan City - Bagong Silang Campus.

Student Name: {student_name}
Date: {formatted_date}
Time: {formatted_time}

This notification is automatically generated by our campus entry system. Please contact the administration for any inquiries.

Sincerely,
University of Caloocan City - Bagong Silang
Citadel

---
This is an automated notification. Please do not reply to this email.
© {datetime.now().year} University of Caloocan City - Bagong Silang Campus. All rights reserved.
"""
    alt.attach(MIMEText(plain, "plain"))

    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{notification_title}</title></head>
<body style="margin:0;padding:0;font-family:'Segoe UI',sans-serif;background:#f5f5f5;">
<table style="width:100%;background:#f5f5f5;padding:20px;" align="center">
<tr><td align="center">
<table style="max-width:600px;width:100%;background:#fff;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);overflow:hidden;">
<tr>
<td style="background:linear-gradient(135deg,#064F32,#053d27);padding:40px 20px;">
<table style="width:100%;">
<tr>
{f"<td style='width:{UCC_LOGO_WIDTH}px;'><img src='cid:ucc_logo' style='width:{UCC_LOGO_WIDTH}px;height:{UCC_LOGO_HEIGHT}px;object-fit:contain;'/></td>" if ucc_logo_path else f"<td style='width:{UCC_LOGO_WIDTH}px;'></td>"}
<td style="text-align:center;">
<h1 style="color:#fff;margin:0;font-size:24px;">University of Caloocan City</h1>
<p style="color:#fff;margin:0;font-size:15px;font-weight:bold;">Bagong Silang Campus</p>
</td>
{f"<td style='width:{LOGO_WIDTH}px;text-align:right;'><img src='cid:logo' style='width:{LOGO_WIDTH}px;height:{LOGO_HEIGHT}px;object-fit:contain;'/></td>" if logo_path else f"<td style='width:{LOGO_WIDTH}px;'></td>"}
</tr></table></td></tr>
<tr><td style="padding:40px 35px;">
<h2 style="color:#064F32;margin:0 0 25px 0;font-size:24px;">{notification_title}</h2>
<p>Dear Parent/Guardian,</p>
<p>Your child, <b style="color:#064F32;">{student_name}</b>, has {action_text} the University of Caloocan City - Bagong Silang Campus.</p>
<div style="background:#f0f9f4;border-left:5px solid #064F32;padding:25px;margin:30px 0;border-radius:6px;">
<p><b style="color:#064F32;">Student Name:</b> {student_name}</p>
<p><b style="color:#064F32;">Date:</b> {formatted_date}</p>
<p><b style="color:#064F32;">Time:</b> {formatted_time}</p>
</div>
<p>This notification is automatically generated by our campus entry system.</p>
<p>Thank you for your attention.<br><br>
<b style="color:#064F32;">University of Caloocan City - Bagong Silang</b><br>
<span style="color:#666;">Citadel</span></p>
</td></tr>
<tr><td style="background:#f8f9fa;padding:20px;text-align:center;color:#666;font-size:12px;">
<p>This is an automated notification. Please do not reply.</p>
<p>© {datetime.now().year} University of Caloocan City - Bagong Silang Campus. All rights reserved.</p>
</td></tr>
</table></td></tr></table></body></html>"""
    alt.attach(MIMEText(html, "html"))

    for cid, path in [("logo", logo_path), ("ucc_logo", ucc_logo_path)]:
        if path:
            try:
                with open(path, "rb") as f:
                    img_data = f.read()
                    mime_type, _ = guess_type(path)
                    if not mime_type or not mime_type.startswith("image/"):
                        print(f"[WARNING] Invalid{path}")
                        continue
                    subtype = mime_type.split("/")[1]
                    img = MIMEImage(img_data, _subtype=subtype)
                    img.add_header("Content-ID", f"<{cid}>")
                    img.add_header("Content-Disposition", "inline", filename=os.path.basename(path))
                    msg.attach(img)
            except Exception as e:
                print(f"[WARNING] Failed {cid}: {e}")

    smtp = SMTP(hostname=SMTP_CONFIG["host"], port=SMTP_CONFIG["port"], start_tls=SMTP_CONFIG["tls"])
    await smtp.connect()
    await smtp.login(SMTP_CONFIG["user"], SMTP_CONFIG["password"])
    await smtp.send_message(msg)
    await smtp.quit()


async def notify_parent(student_no: str, notification_type: str = "entry"):
    if not has_internet():
        return

    try:
        conn, _ = get_connection()
        cur = conn.cursor()
        cur.execute("""
            SELECT fullname, guardian_email
            FROM students
            WHERE student_no = %s
        """, (student_no,))
        result = cur.fetchone()
        cur.close()
        conn.close()

        if not result:
            print(f"[WARNING] Not found {student_no}")
            return

        student_name, guardian_email = result
        if not guardian_email:
            print(f"[WARNING] No email {student_name}")
            return

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        await send_campus_notification(guardian_email, student_name, timestamp, notification_type)

    except Error as e:
        print(f"[DB ERROR] {e}")


def notify_parent_task(student_no: str, notification_type: str = "entry"):
    def runner():
        asyncio.run(notify_parent(student_no, notification_type))
    threading.Thread(target=runner, daemon=True).start()


def notify_entry(student_no: str):
    notify_parent_task(student_no, "entry")


def notify_exit(student_no: str):
    notify_parent_task(student_no, "exit")