# Form implementation generated from reading ui file 'enroll.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EnrollWindow(object):
    def setupUi(self, EnrollWindow):
        EnrollWindow.setObjectName("EnrollWindow")
        EnrollWindow.resize(1282, 720)
        EnrollWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/logo-enroll.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EnrollWindow.setWindowIcon(icon)
        EnrollWindow.setStyleSheet("* {\n"
"    font-family: \'Poppins-Regular\', sans-serif;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#titleWidget {\n"
"    background-color: #064f32;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QWidget#bodyWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#detailsWidget {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#cameraWidget {\n"
"    background-color: #fff;\n"
"    border-radius: 20px\n"
"}\n"
"\n"
"QWidget#footerWidget {\n"
"    background-color: #064f32;\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel#schoolNameLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolSubLabel {\n"
"    color: #fff;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel {\n"
"    color: #fff;\n"
"    font-weight: 900;\n"
"}\n"
"\n"
"QLabel#footerLabel {\n"
"    color: #fff;\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel#cameraFeed {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QPushButton#btnFace,\n"
"QPushButton#btnFinger {\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: #ffffff;\n"
"    color: #4CAF50;\n"
"    padding: 8px 18px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"QPushButton#btnFace {\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"QPushButton#btnFinger {\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"QPushButton#btnFace:hover,\n"
"QPushButton#btnFinger:hover {\n"
"    background-color: #E6F5E8;\n"
"}\n"
"\n"
"QPushButton#btnFace:pressed,\n"
"QPushButton#btnFinger:pressed {\n"
"    background-color: #D3EDD7;\n"
"}\n"
"\n"
"QPushButton#btnFace:checked,\n"
"QPushButton#btnFinger:checked {\n"
"    background-color: #4CAF50;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#btnFace:checked:hover,\n"
"QPushButton#btnFinger:checked:hover {\n"
"    background-color: #43A047;\n"
"}\n"
"\n"
"QPushButton#btnSubmit {\n"
"    border-radius: 12px;\n"
"    border: none;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"QPushButton#btnSubmit:hover {\n"
"    background-color: #43A047; \n"
"}\n"
"\n"
"QPushButton#btnSubmit:pressed {\n"
"    background-color: #3C8F3F;\n"
"}\n"
"\n"
"QLineEdit#txtStudentNo {\n"
"    border: 2px solid #777;\n"
"    border-radius: 10px;\n"
"    padding: 4px 8px;\n"
"    background-color: #f9f9f9;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    border-radius: 10px;\n"
"    background-color: #eee;\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=EnrollWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidget = QtWidgets.QGridLayout(self.centralwidget)
        self.centralWidget.setContentsMargins(0, 0, 0, 0)
        self.centralWidget.setSpacing(0)
        self.centralWidget.setObjectName("centralWidget")
        self.enrollLayout = QtWidgets.QGridLayout()
        self.enrollLayout.setSpacing(0)
        self.enrollLayout.setObjectName("enrollLayout")
        self.footerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.footerWidget.setMinimumSize(QtCore.QSize(1280, 120))
        self.footerWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.footerWidget.setObjectName("footerWidget")
        self.footerLayout = QtWidgets.QHBoxLayout(self.footerWidget)
        self.footerLayout.setContentsMargins(0, 0, 0, 0)
        self.footerLayout.setSpacing(0)
        self.footerLayout.setObjectName("footerLayout")
        self.footerLabel = QtWidgets.QLabel(parent=self.footerWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(16)
        font.setBold(True)
        self.footerLabel.setFont(font)
        self.footerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.footerLabel.setObjectName("footerLabel")
        self.footerLayout.addWidget(self.footerLabel)
        self.enrollLayout.addWidget(self.footerWidget, 2, 0, 1, 1)
        self.bodyWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.bodyWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.bodyWidget.setObjectName("bodyWidget")
        self.bodyLayout = QtWidgets.QHBoxLayout(self.bodyWidget)
        self.bodyLayout.setContentsMargins(11, 11, 11, 11)
        self.bodyLayout.setSpacing(10)
        self.bodyLayout.setObjectName("bodyLayout")
        self.cameraWidget = QtWidgets.QWidget(parent=self.bodyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraWidget.sizePolicy().hasHeightForWidth())
        self.cameraWidget.setSizePolicy(sizePolicy)
        self.cameraWidget.setObjectName("cameraWidget")
        self.cameraLayout = QtWidgets.QHBoxLayout(self.cameraWidget)
        self.cameraLayout.setContentsMargins(11, 0, 11, 0)
        self.cameraLayout.setSpacing(0)
        self.cameraLayout.setObjectName("cameraLayout")
        self.cameraFeed = QtWidgets.QLabel(parent=self.cameraWidget)
        self.cameraFeed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFeed.sizePolicy().hasHeightForWidth())
        self.cameraFeed.setSizePolicy(sizePolicy)
        self.cameraFeed.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraFeed.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.cameraFeed.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraFeed.setText("")
        self.cameraFeed.setScaledContents(False)
        self.cameraFeed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraFeed.setObjectName("cameraFeed")
        self.cameraLayout.addWidget(self.cameraFeed)
        self.bodyLayout.addWidget(self.cameraWidget)
        self.detailsWidget = QtWidgets.QWidget(parent=self.bodyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailsWidget.sizePolicy().hasHeightForWidth())
        self.detailsWidget.setSizePolicy(sizePolicy)
        self.detailsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.detailsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detailsWidget.setObjectName("detailsWidget")
        self.detailsLayout = QtWidgets.QVBoxLayout(self.detailsWidget)
        self.detailsLayout.setContentsMargins(33, 33, 33, 44)
        self.detailsLayout.setSpacing(0)
        self.detailsLayout.setObjectName("detailsLayout")
        self.addStudentLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStudentLabel.sizePolicy().hasHeightForWidth())
        self.addStudentLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(20)
        font.setBold(True)
        self.addStudentLabel.setFont(font)
        self.addStudentLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addStudentLabel.setWordWrap(True)
        self.addStudentLabel.setObjectName("addStudentLabel")
        self.detailsLayout.addWidget(self.addStudentLabel)
        self.buttonWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonWidget.sizePolicy().hasHeightForWidth())
        self.buttonWidget.setSizePolicy(sizePolicy)
        self.buttonWidget.setObjectName("buttonWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setSpacing(0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnFace = QtWidgets.QPushButton(parent=self.buttonWidget)
        self.btnFace.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        font.setBold(True)
        self.btnFace.setFont(font)
        self.btnFace.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFace.setObjectName("btnFace")
        self.buttonLayout.addWidget(self.btnFace)
        self.btnFinger = QtWidgets.QPushButton(parent=self.buttonWidget)
        self.btnFinger.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        font.setBold(True)
        self.btnFinger.setFont(font)
        self.btnFinger.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFinger.setObjectName("btnFinger")
        self.buttonLayout.addWidget(self.btnFinger)
        self.detailsLayout.addWidget(self.buttonWidget)
        self.txtStudentNo = QtWidgets.QLineEdit(parent=self.detailsWidget)
        self.txtStudentNo.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        self.txtStudentNo.setFont(font)
        self.txtStudentNo.setMaxLength(10)
        self.txtStudentNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtStudentNo.setObjectName("txtStudentNo")
        self.detailsLayout.addWidget(self.txtStudentNo)
        self.btnSubmit = QtWidgets.QPushButton(parent=self.detailsWidget)
        self.btnSubmit.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        font.setBold(True)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSubmit.setObjectName("btnSubmit")
        self.detailsLayout.addWidget(self.btnSubmit)
        self.statusWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusWidget.sizePolicy().hasHeightForWidth())
        self.statusWidget.setSizePolicy(sizePolicy)
        self.statusWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.statusWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.statusWidget.setObjectName("statusWidget")
        self.statusLayout = QtWidgets.QHBoxLayout(self.statusWidget)
        self.statusLayout.setContentsMargins(0, 0, 0, 0)
        self.statusLayout.setSpacing(0)
        self.statusLayout.setObjectName("statusLayout")
        self.lblStatus = QtWidgets.QLabel(parent=self.statusWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        font.setBold(True)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.statusLayout.addWidget(self.lblStatus)
        self.detailsLayout.addWidget(self.statusWidget)
        self.bodyLayout.addWidget(self.detailsWidget)
        self.enrollLayout.addWidget(self.bodyWidget, 1, 0, 1, 1)
        self.titleWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.titleWidget.setMinimumSize(QtCore.QSize(1280, 120))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.titleWidget.setObjectName("titleWidget")
        self.titleLayout = QtWidgets.QHBoxLayout(self.titleWidget)
        self.titleLayout.setObjectName("titleLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.logoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLayout.addWidget(self.logoLabel)
        self.engLogoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.engLogoLabel.sizePolicy().hasHeightForWidth())
        self.engLogoLabel.setSizePolicy(sizePolicy)
        self.engLogoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.engLogoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.engLogoLabel.setText("")
        self.engLogoLabel.setPixmap(QtGui.QPixmap("gui/assets/logo.png"))
        self.engLogoLabel.setScaledContents(True)
        self.engLogoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engLogoLabel.setObjectName("engLogoLabel")
        self.titleLayout.addWidget(self.engLogoLabel)
        self.schoolWidget = QtWidgets.QWidget(parent=self.titleWidget)
        self.schoolWidget.setObjectName("schoolWidget")
        self.schoolLayout = QtWidgets.QVBoxLayout(self.schoolWidget)
        self.schoolLayout.setContentsMargins(0, 0, 0, 0)
        self.schoolLayout.setSpacing(7)
        self.schoolLayout.setObjectName("schoolLayout")
        self.schoolNameLabel = QtWidgets.QLabel(parent=self.schoolWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(25)
        font.setBold(True)
        self.schoolNameLabel.setFont(font)
        self.schoolNameLabel.setObjectName("schoolNameLabel")
        self.schoolLayout.addWidget(self.schoolNameLabel)
        self.schoolSubLabel = QtWidgets.QLabel(parent=self.schoolWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.schoolSubLabel.setFont(font)
        self.schoolSubLabel.setObjectName("schoolSubLabel")
        self.schoolLayout.addWidget(self.schoolSubLabel)
        self.titleLayout.addWidget(self.schoolWidget)
        self.dateTimeLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(29)
        self.dateTimeLabel.setFont(font)
        self.dateTimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.titleLayout.addWidget(self.dateTimeLabel)
        self.syncLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncLabel.sizePolicy().hasHeightForWidth())
        self.syncLabel.setSizePolicy(sizePolicy)
        self.syncLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.syncLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.syncLabel.setText("")
        self.syncLabel.setObjectName("syncLabel")
        self.titleLayout.addWidget(self.syncLabel)
        self.enrollLayout.addWidget(self.titleWidget, 0, 0, 1, 1)
        self.centralWidget.addLayout(self.enrollLayout, 0, 0, 1, 1)
        EnrollWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EnrollWindow)
        QtCore.QMetaObject.connectSlotsByName(EnrollWindow)

    def retranslateUi(self, EnrollWindow):
        _translate = QtCore.QCoreApplication.translate
        EnrollWindow.setWindowTitle(_translate("EnrollWindow", "Enroll"))
        self.footerLabel.setText(_translate("EnrollWindow", "Facial data and fingerprint data are encrypted in cloud. We do not store facial and fingerprint image."))
        self.addStudentLabel.setText(_translate("EnrollWindow", "UPLOAD STUDENT DATA"))
        self.btnFace.setText(_translate("EnrollWindow", "Face Data"))
        self.btnFinger.setText(_translate("EnrollWindow", "Fingerprint"))
        self.txtStudentNo.setPlaceholderText(_translate("EnrollWindow", "Enter student no."))
        self.btnSubmit.setText(_translate("EnrollWindow", "Start"))
        self.schoolNameLabel.setText(_translate("EnrollWindow", "University of Caloocan City"))
        self.schoolSubLabel.setText(_translate("EnrollWindow", "Citadel Enrollment System"))
        self.dateTimeLabel.setText(_translate("EnrollWindow", "JAN 01, 2026 - 12:00PM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnrollWindow = QtWidgets.QMainWindow()
    ui = Ui_EnrollWindow()
    ui.setupUi(EnrollWindow)
    EnrollWindow.show()
    sys.exit(app.exec())
