# Form implementation generated from reading ui file 'enroll.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EnrollWindow(object):
    def setupUi(self, EnrollWindow):
        EnrollWindow.setObjectName("EnrollWindow")
        EnrollWindow.resize(1434, 879)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/UCC_Logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EnrollWindow.setWindowIcon(icon)
        EnrollWindow.setStyleSheet("* {\n"
"    font-family: \'Poppins-Regular\', sans-serif;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#titleWidget {\n"
"    background-color: #064f32;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"QWidget#bodyWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#detailsWidget {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#footerWidget {\n"
"    background-color: #064f32;\n"
"    max-height: 80px;\n"
"}\n"
"\n"
"QLabel#logoLabel {\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    margin: 0px 20px;\n"
"}\n"
"\n"
"QLabel#schoolNameLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    max-width: 500px;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolSubLabel {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QLabel#footerLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel#cameraFeed {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton#btnFace,\n"
"QPushButton#btnFinger {\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: #ffffff;\n"
"    color: #4CAF50;\n"
"    padding: 8px 18px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"QPushButton#btnFace {\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"QPushButton#btnFinger {\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"QPushButton#btnFace:hover,\n"
"QPushButton#btnFinger:hover {\n"
"    background-color: #E6F5E8;\n"
"}\n"
"\n"
"QPushButton#btnFace:pressed,\n"
"QPushButton#btnFinger:pressed {\n"
"    background-color: #D3EDD7;\n"
"}\n"
"\n"
"QPushButton#btnFace:checked,\n"
"QPushButton#btnFinger:checked {\n"
"    background-color: #4CAF50;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#btnFace:checked:hover,\n"
"QPushButton#btnFinger:checked:hover {\n"
"    background-color: #43A047;\n"
"}\n"
"\n"
"QPushButton#btnSubmit {\n"
"    border-radius: 12px;\n"
"    border: none;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"QPushButton#btnSubmit:hover {\n"
"    background-color: #43A047; \n"
"}\n"
"\n"
"QPushButton#btnSubmit:pressed {\n"
"    background-color: #3C8F3F;\n"
"}\n"
"\n"
"QLineEdit#txtStudentNo {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: #f9f9f9;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    border-radius: 10px;\n"
"    padding: 20px 30px;\n"
"    background-color: #eee;\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=EnrollWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.titleWidget.setMinimumSize(QtCore.QSize(1280, 100))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(120, 50))
        self.logoLabel.setMaximumSize(QtCore.QSize(120, 80))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLayout.addWidget(self.logoLabel)
        self.engLogoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.engLogoLabel.sizePolicy().hasHeightForWidth())
        self.engLogoLabel.setSizePolicy(sizePolicy)
        self.engLogoLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.engLogoLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.engLogoLabel.setText("")
        self.engLogoLabel.setPixmap(QtGui.QPixmap("gui/assets/logo.png"))
        self.engLogoLabel.setScaledContents(True)
        self.engLogoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engLogoLabel.setObjectName("engLogoLabel")
        self.titleLayout.addWidget(self.engLogoLabel)
        self.logoSpacer = QtWidgets.QLabel(parent=self.titleWidget)
        self.logoSpacer.setMinimumSize(QtCore.QSize(20, 0))
        self.logoSpacer.setMaximumSize(QtCore.QSize(20, 16777215))
        self.logoSpacer.setText("")
        self.logoSpacer.setObjectName("logoSpacer")
        self.titleLayout.addWidget(self.logoSpacer)
        self.schoolLayout = QtWidgets.QVBoxLayout()
        self.schoolLayout.setObjectName("schoolLayout")
        self.schoolNameLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.schoolNameLabel.setObjectName("schoolNameLabel")
        self.schoolLayout.addWidget(self.schoolNameLabel)
        self.schoolSubLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.schoolSubLabel.setObjectName("schoolSubLabel")
        self.schoolLayout.addWidget(self.schoolSubLabel)
        self.titleLayout.addLayout(self.schoolLayout)
        self.dateTimeLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.dateTimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.titleLayout.addWidget(self.dateTimeLabel)
        self.syncLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncLabel.sizePolicy().hasHeightForWidth())
        self.syncLabel.setSizePolicy(sizePolicy)
        self.syncLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.syncLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.syncLabel.setText("")
        self.syncLabel.setObjectName("syncLabel")
        self.titleLayout.addWidget(self.syncLabel)
        self.horizontalLayout.addLayout(self.titleLayout)
        self.verticalLayout.addWidget(self.titleWidget)
        self.bodyWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.bodyWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.bodyWidget.setObjectName("bodyWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bodyWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cameraLayout = QtWidgets.QHBoxLayout()
        self.cameraLayout.setContentsMargins(0, 22, 0, 22)
        self.cameraLayout.setObjectName("cameraLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout.addItem(spacerItem)
        self.cameraFeed = QtWidgets.QLabel(parent=self.bodyWidget)
        self.cameraFeed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFeed.sizePolicy().hasHeightForWidth())
        self.cameraFeed.setSizePolicy(sizePolicy)
        self.cameraFeed.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraFeed.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.cameraFeed.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraFeed.setText("")
        self.cameraFeed.setScaledContents(False)
        self.cameraFeed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraFeed.setObjectName("cameraFeed")
        self.cameraLayout.addWidget(self.cameraFeed)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.cameraLayout, 0, 0, 1, 1)
        self.detailsContainer = QtWidgets.QWidget(parent=self.bodyWidget)
        self.detailsContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detailsContainer.setObjectName("detailsContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.detailsContainer)
        self.horizontalLayout_3.setContentsMargins(-1, 22, -1, 22)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.detailsLayout = QtWidgets.QVBoxLayout()
        self.detailsLayout.setSpacing(7)
        self.detailsLayout.setObjectName("detailsLayout")
        self.detailsWidget = QtWidgets.QWidget(parent=self.detailsContainer)
        self.detailsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.detailsWidget.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.detailsWidget.setObjectName("detailsWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.detailsWidget)
        self.gridLayout_2.setContentsMargins(100, 75, 100, 75)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.studentNoVerticalLayout = QtWidgets.QVBoxLayout()
        self.studentNoVerticalLayout.setObjectName("studentNoVerticalLayout")
        self.studentNoWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        self.studentNoWidget.setObjectName("studentNoWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.studentNoWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.addStudentLabel = QtWidgets.QLabel(parent=self.studentNoWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(20)
        font.setBold(True)
        self.addStudentLabel.setFont(font)
        self.addStudentLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addStudentLabel.setObjectName("addStudentLabel")
        self.verticalLayout_10.addWidget(self.addStudentLabel)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnFace = QtWidgets.QPushButton(parent=self.studentNoWidget)
        self.btnFace.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        font.setBold(True)
        self.btnFace.setFont(font)
        self.btnFace.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFace.setObjectName("btnFace")
        self.horizontalLayout_9.addWidget(self.btnFace)
        self.btnFinger = QtWidgets.QPushButton(parent=self.studentNoWidget)
        self.btnFinger.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        font.setBold(True)
        self.btnFinger.setFont(font)
        self.btnFinger.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFinger.setObjectName("btnFinger")
        self.horizontalLayout_9.addWidget(self.btnFinger)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.txtStudentNo = QtWidgets.QLineEdit(parent=self.studentNoWidget)
        self.txtStudentNo.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.txtStudentNo.setFont(font)
        self.txtStudentNo.setMaxLength(10)
        self.txtStudentNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtStudentNo.setObjectName("txtStudentNo")
        self.verticalLayout_10.addWidget(self.txtStudentNo)
        self.btnSubmit = QtWidgets.QPushButton(parent=self.studentNoWidget)
        self.btnSubmit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        font.setBold(True)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSubmit.setObjectName("btnSubmit")
        self.verticalLayout_10.addWidget(self.btnSubmit)
        self.studentNoVerticalLayout.addWidget(self.studentNoWidget)
        self.gridLayout_2.addLayout(self.studentNoVerticalLayout, 0, 0, 1, 1)
        self.statusLayout = QtWidgets.QHBoxLayout()
        self.statusLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.statusLayout.setContentsMargins(0, 0, 0, 0)
        self.statusLayout.setSpacing(0)
        self.statusLayout.setObjectName("statusLayout")
        self.statusWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusWidget.sizePolicy().hasHeightForWidth())
        self.statusWidget.setSizePolicy(sizePolicy)
        self.statusWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.statusWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.statusWidget.setObjectName("statusWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.statusWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblStatus = QtWidgets.QLabel(parent=self.statusWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        font.setBold(True)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.horizontalLayout_5.addWidget(self.lblStatus)
        self.statusLayout.addWidget(self.statusWidget)
        self.gridLayout_2.addLayout(self.statusLayout, 1, 0, 1, 1)
        self.detailsLayout.addWidget(self.detailsWidget)
        self.horizontalLayout_3.addLayout(self.detailsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.detailsContainer, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.bodyWidget)
        self.footerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.footerWidget.setMinimumSize(QtCore.QSize(1280, 70))
        self.footerWidget.setObjectName("footerWidget")
        self.footerHBox = QtWidgets.QHBoxLayout(self.footerWidget)
        self.footerHBox.setObjectName("footerHBox")
        self.footerLabel = QtWidgets.QLabel(parent=self.footerWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(10)
        font.setBold(True)
        self.footerLabel.setFont(font)
        self.footerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.footerLabel.setObjectName("footerLabel")
        self.footerHBox.addWidget(self.footerLabel)
        self.verticalLayout.addWidget(self.footerWidget)
        EnrollWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EnrollWindow)
        QtCore.QMetaObject.connectSlotsByName(EnrollWindow)

    def retranslateUi(self, EnrollWindow):
        _translate = QtCore.QCoreApplication.translate
        EnrollWindow.setWindowTitle(_translate("EnrollWindow", "Citadel - Enrollment"))
        self.schoolNameLabel.setText(_translate("EnrollWindow", "University of Caloocan City"))
        self.schoolSubLabel.setText(_translate("EnrollWindow", "Citadel Enrollment System"))
        self.dateTimeLabel.setText(_translate("EnrollWindow", "October 15, 2025 | 05:00AM"))
        self.addStudentLabel.setText(_translate("EnrollWindow", "UPLOAD STUDENT DATA"))
        self.btnFace.setText(_translate("EnrollWindow", "Face Data"))
        self.btnFinger.setText(_translate("EnrollWindow", "Fingerprint"))
        self.txtStudentNo.setPlaceholderText(_translate("EnrollWindow", "Enter student no."))
        self.btnSubmit.setText(_translate("EnrollWindow", "Start"))
        self.footerLabel.setText(_translate("EnrollWindow", "Facial data and fingerprint data are encrypted in cloud. We do not store facial and fingerprint image."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnrollWindow = QtWidgets.QMainWindow()
    ui = Ui_EnrollWindow()
    ui.setupUi(EnrollWindow)
    EnrollWindow.show()
    sys.exit(app.exec())
