# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(600, 500)
        LoginDialog.setStyleSheet("#LoginDialog {\n"
"    background-color: #f7f9fb;\n"
"    border-radius: 14px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #d0d4da;\n"
"    border-radius: 6px;\n"
"    padding: 6px 8px;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    background-color: #E0E0E0;\n"
"    color: #333333;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D5D5D5;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #C8C8C8;\n"
"}\n"
"QPushButton#loginBtn {\n"
"    background-color: #4CAF50;\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton#loginBtn:hover {\n"
"    background-color: #43A047;\n"
"}\n"
"QPushButton#loginBtn:pressed {\n"
"    background-color: #3C8F3F;\n"
"}\n"
"QPushButton#editConnBtn {\n"
"    background-color: #FFE0B2;\n"
"    color: #5D4037;\n"
"}\n"
"QPushButton#editConnBtn:hover {\n"
"    background-color: #FFE0B2;\n"
"}\n"
"QPushButton#editConnBtn:pressed {\n"
"    background-color: #FFE0B2;\n"
"}\n"
"QCheckBox {\n"
"    font-size: 11px;\n"
"    color: #555;\n"
"}\n"
"QLabel#statusLabel {\n"
"    color: #c0392b;\n"
"    font-size: 11px;\n"
"}\n"
"QLabel#titleLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #064F32;\n"
"}\n"
"QLabel#subtitleLabel {\n"
"    font-size: 12px;\n"
"    color: #555;\n"
"}\n"
"QLabel#termsLink {\n"
"    color: #064F32;\n"
"    font-size: 10px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(LoginDialog)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=LoginDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.logoLabel.setMinimumSize(QtCore.QSize(72, 72))
        self.logoLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("gui/assets/ucc.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.headerLayout.addWidget(self.logoLabel)
        self.textLayout = QtWidgets.QVBoxLayout()
        self.textLayout.setObjectName("textLayout")
        self.titleLabel = QtWidgets.QLabel(parent=LoginDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.textLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(parent=LoginDialog)
        font = QtGui.QFont()
        self.subtitleLabel.setFont(font)
        self.subtitleLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.textLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.textLayout)
        self.citadelLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.citadelLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.citadelLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.citadelLabel.setText("")
        self.citadelLabel.setPixmap(QtGui.QPixmap("gui/assets/logo.png"))
        self.citadelLabel.setScaledContents(True)
        self.citadelLabel.setObjectName("citadelLabel")
        self.headerLayout.addWidget(self.citadelLabel)
        self.gridLayout.addLayout(self.headerLayout, 0, 0, 1, 1)
        self.passEdit = QtWidgets.QLineEdit(parent=LoginDialog)
        self.passEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        self.passEdit.setFont(font)
        self.passEdit.setMaxLength(64)
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passEdit.setObjectName("passEdit")
        self.gridLayout.addWidget(self.passEdit, 3, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.statusLabel.setText("")
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 5, 0, 1, 1)
        self.userEdit = QtWidgets.QLineEdit(parent=LoginDialog)
        self.userEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.userEdit.setMaxLength(64)
        self.userEdit.setClearButtonEnabled(True)
        self.userEdit.setObjectName("userEdit")
        self.gridLayout.addWidget(self.userEdit, 2, 0, 1, 1)
        self.rememberMeCb = QtWidgets.QCheckBox(parent=LoginDialog)
        self.rememberMeCb.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rememberMeCb.setObjectName("rememberMeCb")
        self.gridLayout.addWidget(self.rememberMeCb, 4, 0, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.cancelBtn = QtWidgets.QPushButton(parent=LoginDialog)
        self.cancelBtn.setMinimumSize(QtCore.QSize(80, 45))
        self.cancelBtn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonLayout.addWidget(self.cancelBtn)
        self.label_2 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_2.setMinimumSize(QtCore.QSize(20, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.buttonLayout.addWidget(self.label_2)
        self.loginBtn = QtWidgets.QPushButton(parent=LoginDialog)
        self.loginBtn.setMinimumSize(QtCore.QSize(80, 45))
        self.loginBtn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")
        self.buttonLayout.addWidget(self.loginBtn)
        self.gridLayout.addLayout(self.buttonLayout, 7, 0, 1, 1)
        self.termsLink = QtWidgets.QLabel(parent=LoginDialog)
        self.termsLink.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.termsLink.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.termsLink.setOpenExternalLinks(False)
        self.termsLink.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.termsLink.setObjectName("termsLink")
        self.gridLayout.addWidget(self.termsLink, 6, 0, 1, 1)
        self.editConnBtn = QtWidgets.QPushButton(parent=LoginDialog)
        self.editConnBtn.setMinimumSize(QtCore.QSize(160, 36))
        self.editConnBtn.setMaximumSize(QtCore.QSize(160, 36))
        self.editConnBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editConnBtn.setFlat(True)
        self.editConnBtn.setObjectName("editConnBtn")
        self.gridLayout.addWidget(self.editConnBtn, 9, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(parent=LoginDialog)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Citadel Login"))
        self.titleLabel.setText(_translate("LoginDialog", "University of Caloocan City"))
        self.subtitleLabel.setText(_translate("LoginDialog", "Citadel Enrollment Login"))
        self.passEdit.setPlaceholderText(_translate("LoginDialog", "Password"))
        self.userEdit.setPlaceholderText(_translate("LoginDialog", "Username or Email"))
        self.rememberMeCb.setText(_translate("LoginDialog", "Remember me"))
        self.cancelBtn.setText(_translate("LoginDialog", "Exit"))
        self.loginBtn.setText(_translate("LoginDialog", "Login"))
        self.termsLink.setText(_translate("LoginDialog", "View <a href=\"#\">Terms and Conditions / Privacy Notice</a>"))
        self.editConnBtn.setText(_translate("LoginDialog", "Edit connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
