# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Citadel(object):
    def setupUi(self, Citadel):
        Citadel.setObjectName("Citadel")
        Citadel.resize(1280, 720)
        Citadel.setMinimumSize(QtCore.QSize(520, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/UCC_Logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Citadel.setWindowIcon(icon)
        Citadel.setAutoFillBackground(False)
        Citadel.setStyleSheet("* {\n"
"    font-family: Poppins;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#titleWidget {\n"
"    background-color: #064f32;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QWidget#bodyWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#displayWidget {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#detailsWidget {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#monitorWidget {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#footerWidget {\n"
"    background-color: #064f32;\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel#schoolNameLabel {\n"
"    color: #fff;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolSubLabel {\n"
"    color: #fff;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel {\n"
"    color: #fff;\n"
"    font-weight: 900;\n"
"}\n"
"\n"
"QLabel#footerLabel {\n"
"    color: #fff;\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel#nameLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#entryLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#idLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#programLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#statusLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#statusLabelExit {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#cameraFeed_2 {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel#cameraFeedExit {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel#firstDetailLabel,\n"
"QLabel#secondDetailLabel,\n"
"QLabel#thirdDetailLabel,\n"
"QLabel#firstdetailLabel,\n"
"QLabel#seconddetailLabel,\n"
"QLabel#thirddetailLabel {\n"
"    color: #FFFFFF;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    min-height: 100px;\n"
"    font-weight: 900;\n"
"}\n"
"\n"
"QLabel#firstDetailLabel,\n"
"QLabel#firstdetailLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #064f32,\n"
"        stop:0.02 #064f32,\n"
"        stop:0.03 #2F8057,\n"
"        stop:1 #0E603C);\n"
"}\n"
"\n"
"QLabel#secondDetailLabel,\n"
"QLabel#seconddetailLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #1c855a,\n"
"        stop:0.02 #1c855a,\n"
"        stop:0.03 #5FB18A,\n"
"        stop:1 #2E916A);\n"
"}\n"
"\n"
"QLabel#thirdDetailLabel,\n"
"QLabel#thirddetailLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3C8F3F,\n"
"        stop:0.02 #3C8F3F,\n"
"        stop:0.03 #7BC67F,\n"
"        stop:1 #4A9B4E);\n"
"}\n"
"\n"
"\n"
"QPushButton#btnFace,\n"
"QPushButton#btnFinger {\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: #ffffff;\n"
"    color: #4CAF50;\n"
"    padding: 8px 18px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"/* left button rounded */\n"
"QPushButton#btnFace {\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"/* right button rounded */\n"
"QPushButton#btnFinger {\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"/* hover (unselected) */\n"
"QPushButton#btnFace:hover,\n"
"QPushButton#btnFinger:hover {\n"
"    background-color: #E6F5E8;\n"
"}\n"
"\n"
"/* pressed */\n"
"QPushButton#btnFace:pressed,\n"
"QPushButton#btnFinger:pressed {\n"
"    background-color: #D3EDD7;\n"
"}\n"
"\n"
"/* CHECKED — show selected */\n"
"QPushButton#btnFace:checked,\n"
"QPushButton#btnFinger:checked {\n"
"    background-color: #4CAF50;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* hover while selected */\n"
"QPushButton#btnFace:checked:hover,\n"
"QPushButton#btnFinger:checked:hover {\n"
"    background-color: #43A047;\n"
"}\n"
"\n"
"QPushButton#btnSubmit {\n"
"    border-radius: 12px;\n"
"    border: none;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"QPushButton#btnSubmit:hover {\n"
"    background-color: #43A047; \n"
"}\n"
"\n"
"QPushButton#btnSubmit:pressed {\n"
"    background-color: #3C8F3F;\n"
"}\n"
"\n"
"QLineEdit#txtStudentNo {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: #f9f9f9;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    border-radius: 10px;\n"
"    padding: 20px 30px;\n"
"    background-color: #eee;\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Default button style in toolbar */\n"
"\n"
"QToolBar{\n"
"    background: white;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background: transparent;\n"
"    padding: 5px 10px;\n"
"    margin: 2px 6px;\n"
"    border-radius: 8px;\n"
"    min-width: 100px;\n"
"    color: #333;\n"
"}\n"
"\n"
"/* Hover */\n"
"QToolBar QToolButton:hover {\n"
"    background: #1c855a;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Pressed */\n"
"QToolBar QToolButton:pressed {\n"
"    background: #064f32;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Checked (active tab) */\n"
"QToolBar QToolButton:checked {\n"
"    background: #064f32;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Citadel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.titleWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.titleWidget.setEnabled(True)
        self.titleWidget.setMinimumSize(QtCore.QSize(1280, 120))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.titleWidget.setObjectName("titleWidget")
        self.titleLayout = QtWidgets.QHBoxLayout(self.titleWidget)
        self.titleLayout.setContentsMargins(10, 10, 10, 10)
        self.titleLayout.setSpacing(10)
        self.titleLayout.setObjectName("titleLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.logoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLayout.addWidget(self.logoLabel)
        self.projectLogoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.projectLogoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.projectLogoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.projectLogoLabel.setText("")
        self.projectLogoLabel.setPixmap(QtGui.QPixmap("gui/assets/logo.png"))
        self.projectLogoLabel.setScaledContents(True)
        self.projectLogoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.projectLogoLabel.setObjectName("projectLogoLabel")
        self.titleLayout.addWidget(self.projectLogoLabel)
        self.schoolWidget = QtWidgets.QWidget(parent=self.titleWidget)
        self.schoolWidget.setObjectName("schoolWidget")
        self.schoolLayout = QtWidgets.QVBoxLayout(self.schoolWidget)
        self.schoolLayout.setContentsMargins(0, 0, 0, 0)
        self.schoolLayout.setSpacing(7)
        self.schoolLayout.setObjectName("schoolLayout")
        self.schoolNameLabel = QtWidgets.QLabel(parent=self.schoolWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(25)
        font.setBold(True)
        self.schoolNameLabel.setFont(font)
        self.schoolNameLabel.setScaledContents(True)
        self.schoolNameLabel.setObjectName("schoolNameLabel")
        self.schoolLayout.addWidget(self.schoolNameLabel)
        self.schoolSubLabel = QtWidgets.QLabel(parent=self.schoolWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.schoolSubLabel.setFont(font)
        self.schoolSubLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.schoolSubLabel.setObjectName("schoolSubLabel")
        self.schoolLayout.addWidget(self.schoolSubLabel)
        self.titleLayout.addWidget(self.schoolWidget)
        self.dateTimeLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(29)
        self.dateTimeLabel.setFont(font)
        self.dateTimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.titleLayout.addWidget(self.dateTimeLabel)
        self.onlineLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.onlineLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.onlineLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.onlineLabel.setText("")
        self.onlineLabel.setScaledContents(True)
        self.onlineLabel.setObjectName("onlineLabel")
        self.titleLayout.addWidget(self.onlineLabel)
        self.mainLayout.addWidget(self.titleWidget)
        self.bodyWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.bodyWidget.setEnabled(True)
        self.bodyWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.bodyWidget.setAutoFillBackground(False)
        self.bodyWidget.setObjectName("bodyWidget")
        self.bodyLayout = QtWidgets.QHBoxLayout(self.bodyWidget)
        self.bodyLayout.setContentsMargins(11, 11, 11, 11)
        self.bodyLayout.setSpacing(11)
        self.bodyLayout.setObjectName("bodyLayout")
        self.displayWidget = QtWidgets.QWidget(parent=self.bodyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayWidget.sizePolicy().hasHeightForWidth())
        self.displayWidget.setSizePolicy(sizePolicy)
        self.displayWidget.setObjectName("displayWidget")
        self.displayLayout = QtWidgets.QGridLayout(self.displayWidget)
        self.displayLayout.setContentsMargins(0, 0, 0, 0)
        self.displayLayout.setVerticalSpacing(0)
        self.displayLayout.setObjectName("displayLayout")
        self.detailsWidget = QtWidgets.QWidget(parent=self.displayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailsWidget.sizePolicy().hasHeightForWidth())
        self.detailsWidget.setSizePolicy(sizePolicy)
        self.detailsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.detailsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detailsWidget.setObjectName("detailsWidget")
        self.detailsLayout = QtWidgets.QVBoxLayout(self.detailsWidget)
        self.detailsLayout.setContentsMargins(34, 30, 34, 30)
        self.detailsLayout.setSpacing(5)
        self.detailsLayout.setObjectName("detailsLayout")
        self.label = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.detailsLayout.addWidget(self.label)
        self.spacerLabel_1 = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.spacerLabel_1.sizePolicy().hasHeightForWidth())
        self.spacerLabel_1.setSizePolicy(sizePolicy)
        self.spacerLabel_1.setMinimumSize(QtCore.QSize(0, 50))
        self.spacerLabel_1.setText("")
        self.spacerLabel_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spacerLabel_1.setObjectName("spacerLabel_1")
        self.detailsLayout.addWidget(self.spacerLabel_1)
        self.nameLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        font.setBold(True)
        self.nameLabel.setFont(font)
        self.nameLabel.setAutoFillBackground(False)
        self.nameLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.nameLabel.setScaledContents(True)
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLabel.setWordWrap(True)
        self.nameLabel.setObjectName("nameLabel")
        self.detailsLayout.addWidget(self.nameLabel)
        self.programLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.programLabel.sizePolicy().hasHeightForWidth())
        self.programLabel.setSizePolicy(sizePolicy)
        self.programLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.programLabel.setFont(font)
        self.programLabel.setAutoFillBackground(False)
        self.programLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.programLabel.setScaledContents(True)
        self.programLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.programLabel.setWordWrap(True)
        self.programLabel.setObjectName("programLabel")
        self.detailsLayout.addWidget(self.programLabel)
        self.yearSecLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.yearSecLabel.sizePolicy().hasHeightForWidth())
        self.yearSecLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.yearSecLabel.setFont(font)
        self.yearSecLabel.setScaledContents(True)
        self.yearSecLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yearSecLabel.setWordWrap(True)
        self.yearSecLabel.setObjectName("yearSecLabel")
        self.detailsLayout.addWidget(self.yearSecLabel)
        self.idLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.idLabel.sizePolicy().hasHeightForWidth())
        self.idLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.idLabel.setFont(font)
        self.idLabel.setAutoFillBackground(False)
        self.idLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.idLabel.setScaledContents(True)
        self.idLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.idLabel.setWordWrap(True)
        self.idLabel.setObjectName("idLabel")
        self.detailsLayout.addWidget(self.idLabel)
        self.entryLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.entryLabel.sizePolicy().hasHeightForWidth())
        self.entryLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.entryLabel.setFont(font)
        self.entryLabel.setAutoFillBackground(False)
        self.entryLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.entryLabel.setScaledContents(True)
        self.entryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.entryLabel.setWordWrap(True)
        self.entryLabel.setObjectName("entryLabel")
        self.detailsLayout.addWidget(self.entryLabel)
        self.statusWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        self.statusWidget.setMinimumSize(QtCore.QSize(100, 50))
        self.statusWidget.setObjectName("statusWidget")
        self.statusLayout = QtWidgets.QHBoxLayout(self.statusWidget)
        self.statusLayout.setContentsMargins(55, 0, 55, 0)
        self.statusLayout.setSpacing(0)
        self.statusLayout.setObjectName("statusLayout")
        self.statusLabel = QtWidgets.QLabel(parent=self.statusWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.statusLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setAutoFillBackground(False)
        self.statusLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.statusLabel.setText("")
        self.statusLabel.setScaledContents(True)
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")
        self.statusLayout.addWidget(self.statusLabel)
        self.detailsLayout.addWidget(self.statusWidget)
        self.displayLayout.addWidget(self.detailsWidget, 0, 0, 1, 1)
        self.bodyLayout.addWidget(self.displayWidget)
        self.monitorWidget = QtWidgets.QWidget(parent=self.bodyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorWidget.sizePolicy().hasHeightForWidth())
        self.monitorWidget.setSizePolicy(sizePolicy)
        self.monitorWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.monitorWidget.setObjectName("monitorWidget")
        self.monitorLayout = QtWidgets.QVBoxLayout(self.monitorWidget)
        self.monitorLayout.setContentsMargins(34, 30, 34, 30)
        self.monitorLayout.setSpacing(20)
        self.monitorLayout.setObjectName("monitorLayout")
        self.summaryLabel = QtWidgets.QLabel(parent=self.monitorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.summaryLabel.sizePolicy().hasHeightForWidth())
        self.summaryLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        self.summaryLabel.setFont(font)
        self.summaryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.summaryLabel.setObjectName("summaryLabel")
        self.monitorLayout.addWidget(self.summaryLabel)
        self.firstDetailLabel = QtWidgets.QLabel(parent=self.monitorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.firstDetailLabel.sizePolicy().hasHeightForWidth())
        self.firstDetailLabel.setSizePolicy(sizePolicy)
        self.firstDetailLabel.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.firstDetailLabel.setFont(font)
        self.firstDetailLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.firstDetailLabel.setObjectName("firstDetailLabel")
        self.monitorLayout.addWidget(self.firstDetailLabel)
        self.secondDetailLabel = QtWidgets.QLabel(parent=self.monitorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.secondDetailLabel.sizePolicy().hasHeightForWidth())
        self.secondDetailLabel.setSizePolicy(sizePolicy)
        self.secondDetailLabel.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setKerning(True)
        self.secondDetailLabel.setFont(font)
        self.secondDetailLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.secondDetailLabel.setObjectName("secondDetailLabel")
        self.monitorLayout.addWidget(self.secondDetailLabel)
        self.thirdDetailLabel = QtWidgets.QLabel(parent=self.monitorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.thirdDetailLabel.sizePolicy().hasHeightForWidth())
        self.thirdDetailLabel.setSizePolicy(sizePolicy)
        self.thirdDetailLabel.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setKerning(True)
        self.thirdDetailLabel.setFont(font)
        self.thirdDetailLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.thirdDetailLabel.setObjectName("thirdDetailLabel")
        self.monitorLayout.addWidget(self.thirdDetailLabel)
        self.bodyLayout.addWidget(self.monitorWidget)
        self.mainLayout.addWidget(self.bodyWidget)
        self.footerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.footerWidget.setMinimumSize(QtCore.QSize(1280, 120))
        self.footerWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.footerWidget.setObjectName("footerWidget")
        self.footerLayout = QtWidgets.QHBoxLayout(self.footerWidget)
        self.footerLayout.setContentsMargins(50, 0, 50, 0)
        self.footerLayout.setSpacing(10)
        self.footerLayout.setObjectName("footerLayout")
        self.footerLabel = QtWidgets.QLabel(parent=self.footerWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(True)
        self.footerLabel.setFont(font)
        self.footerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.footerLabel.setWordWrap(False)
        self.footerLabel.setObjectName("footerLabel")
        self.footerLayout.addWidget(self.footerLabel)
        self.mainLayout.addWidget(self.footerWidget)
        self.gridLayout_2.addLayout(self.mainLayout, 0, 0, 1, 1)
        Citadel.setCentralWidget(self.centralwidget)

        self.retranslateUi(Citadel)
        QtCore.QMetaObject.connectSlotsByName(Citadel)

    def retranslateUi(self, Citadel):
        _translate = QtCore.QCoreApplication.translate
        Citadel.setWindowTitle(_translate("Citadel", "Citadel"))
        self.schoolNameLabel.setText(_translate("Citadel", "University of Caloocan City"))
        self.schoolSubLabel.setText(_translate("Citadel", "Citadel Monitoring System"))
        self.dateTimeLabel.setText(_translate("Citadel", "JAN 01, 2026 - 12:00AM"))
        self.label.setText(_translate("Citadel", "STUDENT DATA"))
        self.nameLabel.setText(_translate("Citadel", "Name"))
        self.programLabel.setText(_translate("Citadel", "Program"))
        self.yearSecLabel.setText(_translate("Citadel", "Year and Section"))
        self.idLabel.setText(_translate("Citadel", "ID"))
        self.entryLabel.setText(_translate("Citadel", "Time"))
        self.summaryLabel.setText(_translate("Citadel", "SUMMARY"))
        self.firstDetailLabel.setText(_translate("Citadel", "STUDENTS INSIDE"))
        self.secondDetailLabel.setText(_translate("Citadel", "STUDENTS OUTSIDE"))
        self.thirdDetailLabel.setText(_translate("Citadel", "TOTAL NO. OF STUDENTS"))
        self.footerLabel.setText(_translate("Citadel", "Welcome to University of Caloocan City | Please scan your QR code and verify through biometrics for secure access."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Citadel = QtWidgets.QMainWindow()
    ui = Ui_Citadel()
    ui.setupUi(Citadel)
    Citadel.show()
    sys.exit(app.exec())
