# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Citadel(object):
    def setupUi(self, Citadel):
        Citadel.setObjectName("Citadel")
        Citadel.resize(1326, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/UCC_Logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Citadel.setWindowIcon(icon)
        Citadel.setAutoFillBackground(False)
        Citadel.setStyleSheet("* {\n"
"    font-family: \'Poppins-Regular\', sans-serif;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #F6F7FB;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background-color: #F6F7FB;\n"
"}\n"
"\n"
"QWidget#titleWidget {\n"
"    background-color: #064f32;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"QWidget#titleWidget_2 {\n"
"    background-color: #064f32;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"QWidget#bodyWidget {\n"
"    background-color: #F6F7FB;\n"
"}\n"
"\n"
"QWidget#bodyWidget_2 {\n"
"    background-color: #F6F7FB;\n"
"}\n"
"\n"
"QWidget#detailsWidget {\n"
"        background-color: #FFFFFF;\n"
"}\n"
"\n"
"QWidget#detailsWidget_2 {\n"
"        background-color: #FFFFFF;\n"
"}\n"
"\n"
"QWidget#footerWidget {\n"
"    background-color: #064f32;\n"
"    max-height: 80px;\n"
"}\n"
"\n"
"QWidget#footerWidget_2 {\n"
"    background-color: #064f32;\n"
"    max-height: 80px;\n"
"}\n"
"\n"
"QLabel#logoLabel {\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    margin: 0px 20px;\n"
"}\n"
"\n"
"QLabel#logoLabel_2 {\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    margin: 0px 20px;\n"
"}\n"
"\n"
"QLabel#schoolNameLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    max-width: 500px;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolNameLabel_2 {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    max-width: 500px;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolSubLabel {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#schoolSubLabel_2 {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel_2 {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"\n"
"QLabel#footerLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#footerLabel_2 {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#nameLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#entryLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#idLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#programLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#statusLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#cameraFeed {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#cameraFeed_2 {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QPushButton#btnFace,\n"
"QPushButton#btnFinger,\n"
"QPushButton#btnSubmit {\n"
"    border-radius: 20px; \n"
"    background-color: #4CAF50;       /* green background */\n"
"    color: white;                     /* text color */\n"
"    padding: 6px 12px;                /* vertical/horizontal padding */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btnFace:hover,\n"
"QPushButton#btnFinger:hover,\n"
"QPushButton#btnSubmit:hover {\n"
"    background-color: #45A049;       /* slightly darker on hover */\n"
"}\n"
"\n"
"/* QLineEdit */\n"
"QLineEdit#txtStudentNo {\n"
"    border: 2px solid #ccc;           /* border color */\n"
"    border-radius: 15px;              /* rounded corners */\n"
"    padding: 4px 8px;                 /* inner spacing */\n"
"    background-color: #f9f9f9;        /* light background */\n"
"}\n"
"\n"
"/* QLabel */\n"
"QLabel#lblStatus {\n"
"    border-radius: 12px;                /* optional rounded corners */\n"
"    padding: 4px 8px;\n"
"    background-color: #eee;\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Citadel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.titleWidget = QtWidgets.QWidget(parent=self.page_main)
        self.titleWidget.setEnabled(True)
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(120, 50))
        self.logoLabel.setMaximumSize(QtCore.QSize(120, 80))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLayout.addWidget(self.logoLabel)
        self.engLogoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.engLogoLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.engLogoLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.engLogoLabel.setText("")
        self.engLogoLabel.setPixmap(QtGui.QPixmap("gui/assets/Engineering_Logo.ico"))
        self.engLogoLabel.setScaledContents(True)
        self.engLogoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engLogoLabel.setObjectName("engLogoLabel")
        self.titleLayout.addWidget(self.engLogoLabel)
        self.logoSpacer = QtWidgets.QLabel(parent=self.titleWidget)
        self.logoSpacer.setMinimumSize(QtCore.QSize(20, 0))
        self.logoSpacer.setMaximumSize(QtCore.QSize(20, 16777215))
        self.logoSpacer.setText("")
        self.logoSpacer.setObjectName("logoSpacer")
        self.titleLayout.addWidget(self.logoSpacer)
        self.schoolLayout = QtWidgets.QVBoxLayout()
        self.schoolLayout.setObjectName("schoolLayout")
        self.schoolNameLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.schoolNameLabel.setScaledContents(True)
        self.schoolNameLabel.setObjectName("schoolNameLabel")
        self.schoolLayout.addWidget(self.schoolNameLabel)
        self.schoolSubLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.schoolSubLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.schoolSubLabel.setObjectName("schoolSubLabel")
        self.schoolLayout.addWidget(self.schoolSubLabel)
        self.titleLayout.addLayout(self.schoolLayout)
        self.dateTimeLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.dateTimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.titleLayout.addWidget(self.dateTimeLabel)
        self.horizontalLayout1.addLayout(self.titleLayout)
        self.mainLayout.addWidget(self.titleWidget)
        self.bodyWidget = QtWidgets.QWidget(parent=self.page_main)
        self.bodyWidget.setEnabled(True)
        self.bodyWidget.setMinimumSize(QtCore.QSize(1280, 500))
        self.bodyWidget.setAutoFillBackground(False)
        self.bodyWidget.setObjectName("bodyWidget")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.bodyWidget)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.bodyLayout = QtWidgets.QHBoxLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.cameraLayout = QtWidgets.QHBoxLayout()
        self.cameraLayout.setContentsMargins(-1, 22, -1, 22)
        self.cameraLayout.setObjectName("cameraLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout.addItem(spacerItem)
        self.cameraFeed = QtWidgets.QLabel(parent=self.bodyWidget)
        self.cameraFeed.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraFeed.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.cameraFeed.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraFeed.setText("")
        self.cameraFeed.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.cameraFeed.setScaledContents(False)
        self.cameraFeed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraFeed.setObjectName("cameraFeed")
        self.cameraLayout.addWidget(self.cameraFeed)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout.addItem(spacerItem1)
        self.bodyLayout.addLayout(self.cameraLayout)
        self.detailsContainer = QtWidgets.QWidget(parent=self.bodyWidget)
        self.detailsContainer.setObjectName("detailsContainer")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.detailsContainer)
        self.horizontalLayout3.setContentsMargins(-1, 22, -1, 22)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3.addItem(spacerItem2)
        self.detailsWidget = QtWidgets.QWidget(parent=self.detailsContainer)
        self.detailsWidget.setObjectName("detailsWidget")
        self.verticalLayout3 = QtWidgets.QVBoxLayout(self.detailsWidget)
        self.verticalLayout3.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout3.setSpacing(10)
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.detailsLayout = QtWidgets.QVBoxLayout()
        self.detailsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.detailsLayout.setContentsMargins(50, 50, 50, 0)
        self.detailsLayout.setObjectName("detailsLayout")
        self.nameLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(20)
        font.setBold(True)
        self.nameLabel.setFont(font)
        self.nameLabel.setAutoFillBackground(False)
        self.nameLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.nameLabel.setScaledContents(True)
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLabel.setWordWrap(True)
        self.nameLabel.setObjectName("nameLabel")
        self.detailsLayout.addWidget(self.nameLabel)
        self.programLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        self.programLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(15)
        self.programLabel.setFont(font)
        self.programLabel.setAutoFillBackground(False)
        self.programLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.programLabel.setScaledContents(True)
        self.programLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.programLabel.setWordWrap(True)
        self.programLabel.setObjectName("programLabel")
        self.detailsLayout.addWidget(self.programLabel)
        self.idLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(15)
        self.idLabel.setFont(font)
        self.idLabel.setAutoFillBackground(False)
        self.idLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.idLabel.setScaledContents(True)
        self.idLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.idLabel.setWordWrap(True)
        self.idLabel.setObjectName("idLabel")
        self.detailsLayout.addWidget(self.idLabel)
        self.entryLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(15)
        self.entryLabel.setFont(font)
        self.entryLabel.setAutoFillBackground(False)
        self.entryLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.entryLabel.setScaledContents(True)
        self.entryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.entryLabel.setWordWrap(True)
        self.entryLabel.setObjectName("entryLabel")
        self.detailsLayout.addWidget(self.entryLabel)
        self.spacerLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        self.spacerLabel.setText("")
        self.spacerLabel.setObjectName("spacerLabel")
        self.detailsLayout.addWidget(self.spacerLabel)
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setContentsMargins(125, 10, 125, 10)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.statusWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        self.statusWidget.setMinimumSize(QtCore.QSize(100, 50))
        self.statusWidget.setObjectName("statusWidget")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.statusWidget)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.statusLabel = QtWidgets.QLabel(parent=self.statusWidget)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.statusLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setAutoFillBackground(False)
        self.statusLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.statusLabel.setText("")
        self.statusLabel.setScaledContents(True)
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout5.addWidget(self.statusLabel)
        self.horizontalLayout4.addWidget(self.statusWidget)
        self.detailsLayout.addLayout(self.horizontalLayout4)
        self.label = QtWidgets.QLabel(parent=self.detailsWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.detailsLayout.addWidget(self.label)
        self.verticalLayout3.addLayout(self.detailsLayout)
        self.horizontalLayout3.addWidget(self.detailsWidget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3.addItem(spacerItem3)
        self.bodyLayout.addWidget(self.detailsContainer)
        self.horizontalLayout2.addLayout(self.bodyLayout)
        self.mainLayout.addWidget(self.bodyWidget)
        self.footerWidget = QtWidgets.QWidget(parent=self.page_main)
        self.footerWidget.setMinimumSize(QtCore.QSize(1280, 70))
        self.footerWidget.setObjectName("footerWidget")
        self.footerHBox = QtWidgets.QHBoxLayout(self.footerWidget)
        self.footerHBox.setObjectName("footerHBox")
        self.footerLabel = QtWidgets.QLabel(parent=self.footerWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(10)
        font.setBold(True)
        self.footerLabel.setFont(font)
        self.footerLabel.setWordWrap(False)
        self.footerLabel.setObjectName("footerLabel")
        self.footerHBox.addWidget(self.footerLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.mainLayout.addWidget(self.footerWidget)
        self.verticalLayout.addLayout(self.mainLayout)
        self.stackedWidget.addWidget(self.page_main)
        self.page_enroll = QtWidgets.QWidget()
        self.page_enroll.setObjectName("page_enroll")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_enroll)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.enrollLayout = QtWidgets.QVBoxLayout()
        self.enrollLayout.setObjectName("enrollLayout")
        self.titleWidget_2 = QtWidgets.QWidget(parent=self.page_enroll)
        self.titleWidget_2.setEnabled(True)
        self.titleWidget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidget_2.setObjectName("titleWidget_2")
        self.horizontalLayout1_2 = QtWidgets.QHBoxLayout(self.titleWidget_2)
        self.horizontalLayout1_2.setObjectName("horizontalLayout1_2")
        self.titleLayout_2 = QtWidgets.QHBoxLayout()
        self.titleLayout_2.setObjectName("titleLayout_2")
        self.logoLabel_2 = QtWidgets.QLabel(parent=self.titleWidget_2)
        self.logoLabel_2.setMinimumSize(QtCore.QSize(120, 50))
        self.logoLabel_2.setMaximumSize(QtCore.QSize(120, 80))
        self.logoLabel_2.setText("")
        self.logoLabel_2.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabel_2.setScaledContents(True)
        self.logoLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel_2.setObjectName("logoLabel_2")
        self.titleLayout_2.addWidget(self.logoLabel_2)
        self.engLogoLabel_2 = QtWidgets.QLabel(parent=self.titleWidget_2)
        self.engLogoLabel_2.setMinimumSize(QtCore.QSize(80, 80))
        self.engLogoLabel_2.setMaximumSize(QtCore.QSize(80, 80))
        self.engLogoLabel_2.setText("")
        self.engLogoLabel_2.setPixmap(QtGui.QPixmap("gui/assets/Engineering_Logo.ico"))
        self.engLogoLabel_2.setScaledContents(True)
        self.engLogoLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engLogoLabel_2.setObjectName("engLogoLabel_2")
        self.titleLayout_2.addWidget(self.engLogoLabel_2)
        self.logoSpacer_2 = QtWidgets.QLabel(parent=self.titleWidget_2)
        self.logoSpacer_2.setMinimumSize(QtCore.QSize(20, 0))
        self.logoSpacer_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.logoSpacer_2.setText("")
        self.logoSpacer_2.setObjectName("logoSpacer_2")
        self.titleLayout_2.addWidget(self.logoSpacer_2)
        self.schoolLayout_2 = QtWidgets.QVBoxLayout()
        self.schoolLayout_2.setObjectName("schoolLayout_2")
        self.schoolNameLabel_2 = QtWidgets.QLabel(parent=self.titleWidget_2)
        self.schoolNameLabel_2.setScaledContents(True)
        self.schoolNameLabel_2.setObjectName("schoolNameLabel_2")
        self.schoolLayout_2.addWidget(self.schoolNameLabel_2)
        self.schoolSubLabel_2 = QtWidgets.QLabel(parent=self.titleWidget_2)
        self.schoolSubLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.schoolSubLabel_2.setObjectName("schoolSubLabel_2")
        self.schoolLayout_2.addWidget(self.schoolSubLabel_2)
        self.titleLayout_2.addLayout(self.schoolLayout_2)
        self.dateTimeLabel_2 = QtWidgets.QLabel(parent=self.titleWidget_2)
        self.dateTimeLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeLabel_2.setObjectName("dateTimeLabel_2")
        self.titleLayout_2.addWidget(self.dateTimeLabel_2)
        self.horizontalLayout1_2.addLayout(self.titleLayout_2)
        self.enrollLayout.addWidget(self.titleWidget_2)
        self.bodyWidget_2 = QtWidgets.QWidget(parent=self.page_enroll)
        self.bodyWidget_2.setEnabled(True)
        self.bodyWidget_2.setMinimumSize(QtCore.QSize(1280, 500))
        self.bodyWidget_2.setAutoFillBackground(False)
        self.bodyWidget_2.setObjectName("bodyWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bodyWidget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bodyLayout_2 = QtWidgets.QHBoxLayout()
        self.bodyLayout_2.setObjectName("bodyLayout_2")
        self.cameraLayout_2 = QtWidgets.QHBoxLayout()
        self.cameraLayout_2.setContentsMargins(11, 22, 11, 22)
        self.cameraLayout_2.setObjectName("cameraLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout_2.addItem(spacerItem4)
        self.cameraFeed_2 = QtWidgets.QLabel(parent=self.bodyWidget_2)
        self.cameraFeed_2.setEnabled(True)
        self.cameraFeed_2.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraFeed_2.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.cameraFeed_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraFeed_2.setText("")
        self.cameraFeed_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.cameraFeed_2.setScaledContents(False)
        self.cameraFeed_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraFeed_2.setObjectName("cameraFeed_2")
        self.cameraLayout_2.addWidget(self.cameraFeed_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout_2.addItem(spacerItem5)
        self.bodyLayout_2.addLayout(self.cameraLayout_2)
        self.detailsContainer_2 = QtWidgets.QWidget(parent=self.bodyWidget_2)
        self.detailsContainer_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detailsContainer_2.setObjectName("detailsContainer_2")
        self.horizontalLayout3_2 = QtWidgets.QHBoxLayout(self.detailsContainer_2)
        self.horizontalLayout3_2.setContentsMargins(-1, 22, -1, 22)
        self.horizontalLayout3_2.setObjectName("horizontalLayout3_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3_2.addItem(spacerItem6)
        self.detailsLayout_2 = QtWidgets.QVBoxLayout()
        self.detailsLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.detailsLayout_2.setContentsMargins(0, 0, 0, 0)
        self.detailsLayout_2.setSpacing(7)
        self.detailsLayout_2.setObjectName("detailsLayout_2")
        self.detailsWidget_2 = QtWidgets.QWidget(parent=self.detailsContainer_2)
        self.detailsWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.detailsWidget_2.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.detailsWidget_2.setObjectName("detailsWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.detailsWidget_2)
        self.verticalLayout_3.setContentsMargins(-1, 40, -1, 40)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.studentNoVerticalLayout_3 = QtWidgets.QVBoxLayout()
        self.studentNoVerticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.studentNoVerticalLayout_3.setObjectName("studentNoVerticalLayout_3")
        self.studentNoWidget = QtWidgets.QWidget(parent=self.detailsWidget_2)
        self.studentNoWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.studentNoWidget.setObjectName("studentNoWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.studentNoWidget)
        self.verticalLayout_10.setContentsMargins(60, 70, 60, 20)
        self.verticalLayout_10.setSpacing(15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(parent=self.studentNoWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnFace = QtWidgets.QPushButton(parent=self.studentNoWidget)
        self.btnFace.setMinimumSize(QtCore.QSize(0, 50))
        self.btnFace.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFace.setObjectName("btnFace")
        self.horizontalLayout_9.addWidget(self.btnFace)
        self.btnFinger = QtWidgets.QPushButton(parent=self.studentNoWidget)
        self.btnFinger.setMinimumSize(QtCore.QSize(0, 50))
        self.btnFinger.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFinger.setObjectName("btnFinger")
        self.horizontalLayout_9.addWidget(self.btnFinger)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.txtStudentNo = QtWidgets.QLineEdit(parent=self.studentNoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtStudentNo.sizePolicy().hasHeightForWidth())
        self.txtStudentNo.setSizePolicy(sizePolicy)
        self.txtStudentNo.setMinimumSize(QtCore.QSize(0, 50))
        self.txtStudentNo.setMaxLength(10)
        self.txtStudentNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtStudentNo.setReadOnly(False)
        self.txtStudentNo.setObjectName("txtStudentNo")
        self.verticalLayout_10.addWidget(self.txtStudentNo)
        self.btnSubmit = QtWidgets.QPushButton(parent=self.studentNoWidget)
        self.btnSubmit.setMinimumSize(QtCore.QSize(0, 50))
        self.btnSubmit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        font.setBold(True)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSubmit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnSubmit.setAutoDefault(False)
        self.btnSubmit.setDefault(False)
        self.btnSubmit.setFlat(False)
        self.btnSubmit.setObjectName("btnSubmit")
        self.verticalLayout_10.addWidget(self.btnSubmit)
        self.studentNoVerticalLayout_3.addWidget(self.studentNoWidget)
        self.verticalLayout_3.addLayout(self.studentNoVerticalLayout_3)
        self.statusLayout4_2 = QtWidgets.QHBoxLayout()
        self.statusLayout4_2.setContentsMargins(60, 0, 60, 40)
        self.statusLayout4_2.setObjectName("statusLayout4_2")
        self.statusWidget_2 = QtWidgets.QWidget(parent=self.detailsWidget_2)
        self.statusWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.statusWidget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.statusWidget_2.setObjectName("statusWidget_2")
        self.horizontalLayout5_2 = QtWidgets.QHBoxLayout(self.statusWidget_2)
        self.horizontalLayout5_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5_2.setObjectName("horizontalLayout5_2")
        self.lblStatus = QtWidgets.QLabel(parent=self.statusWidget_2)
        self.lblStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.lblStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        font.setBold(True)
        self.lblStatus.setFont(font)
        self.lblStatus.setAutoFillBackground(False)
        self.lblStatus.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.lblStatus.setText("")
        self.lblStatus.setScaledContents(True)
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setWordWrap(True)
        self.lblStatus.setObjectName("lblStatus")
        self.horizontalLayout5_2.addWidget(self.lblStatus)
        self.statusLayout4_2.addWidget(self.statusWidget_2)
        self.verticalLayout_3.addLayout(self.statusLayout4_2)
        self.detailsLayout_2.addWidget(self.detailsWidget_2)
        self.horizontalLayout3_2.addLayout(self.detailsLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3_2.addItem(spacerItem7)
        self.bodyLayout_2.addWidget(self.detailsContainer_2)
        self.horizontalLayout_4.addLayout(self.bodyLayout_2)
        self.enrollLayout.addWidget(self.bodyWidget_2)
        self.footerWidget_2 = QtWidgets.QWidget(parent=self.page_enroll)
        self.footerWidget_2.setMinimumSize(QtCore.QSize(1280, 70))
        self.footerWidget_2.setObjectName("footerWidget_2")
        self.footerHBox_2 = QtWidgets.QHBoxLayout(self.footerWidget_2)
        self.footerHBox_2.setObjectName("footerHBox_2")
        self.footerLabel_2 = QtWidgets.QLabel(parent=self.footerWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(10)
        font.setBold(True)
        self.footerLabel_2.setFont(font)
        self.footerLabel_2.setWordWrap(False)
        self.footerLabel_2.setObjectName("footerLabel_2")
        self.footerHBox_2.addWidget(self.footerLabel_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.enrollLayout.addWidget(self.footerWidget_2)
        self.verticalLayout_2.addLayout(self.enrollLayout)
        self.stackedWidget.addWidget(self.page_enroll)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.stackedWidget.addWidget(self.page_settings)
        self.verticalLayout1.addWidget(self.stackedWidget)
        Citadel.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=Citadel)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1326, 24))
        self.menuBar.setObjectName("menuBar")
        Citadel.setMenuBar(self.menuBar)

        self.retranslateUi(Citadel)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Citadel)

    def retranslateUi(self, Citadel):
        _translate = QtCore.QCoreApplication.translate
        Citadel.setWindowTitle(_translate("Citadel", "Citadel"))
        self.schoolNameLabel.setText(_translate("Citadel", "University of Caloocan City"))
        self.schoolSubLabel.setText(_translate("Citadel", "Bagong Silang Campus | College of Engineering"))
        self.dateTimeLabel.setText(_translate("Citadel", "October 15, 2025 | 05:00AM"))
        self.nameLabel.setText(_translate("Citadel", "Name"))
        self.programLabel.setText(_translate("Citadel", "Program"))
        self.idLabel.setText(_translate("Citadel", "ID"))
        self.entryLabel.setText(_translate("Citadel", "Time"))
        self.footerLabel.setText(_translate("Citadel", "Welcome to University of Caloocan City | Please scan your QR code and verify through biometrics for secure access."))
        self.schoolNameLabel_2.setText(_translate("Citadel", "University of Caloocan City"))
        self.schoolSubLabel_2.setText(_translate("Citadel", "Bagong Silang Campus | College of Engineering"))
        self.dateTimeLabel_2.setText(_translate("Citadel", "October 15, 2025 | 05:00AM"))
        self.label_2.setText(_translate("Citadel", "ENROLL STUDENT DATA"))
        self.btnFace.setText(_translate("Citadel", "Face Data"))
        self.btnFinger.setText(_translate("Citadel", "Fingerprint"))
        self.txtStudentNo.setPlaceholderText(_translate("Citadel", "Enter student no."))
        self.btnSubmit.setText(_translate("Citadel", "Submit"))
        self.footerLabel_2.setText(_translate("Citadel", "Welcome to University of Caloocan City | Please scan your QR code and verify through biometrics for secure access."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Citadel = QtWidgets.QMainWindow()
    ui = Ui_Citadel()
    ui.setupUi(Citadel)
    Citadel.show()
    sys.exit(app.exec())
