# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Citadel(object):
    def setupUi(self, Citadel):
        Citadel.setObjectName("Citadel")
        Citadel.resize(1280, 720)
        Citadel.setMinimumSize(QtCore.QSize(520, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/UCC_Logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Citadel.setWindowIcon(icon)
        Citadel.setAutoFillBackground(False)
        Citadel.setStyleSheet("\n"
"   \n"
"* {\n"
"    font-family: \'Poppins-Regular\', sans-serif;\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#titleWidget {\n"
"    background-color: #064f32;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"QWidget#titleWidget_2 {\n"
"    background-color: #064f32;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"QWidget#titleWidgetExit {\n"
"    background-color: #064f32;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"\n"
"QWidget#bodyWidget {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#bodyWidget_2 {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#bodyWidgetExit {\n"
"    background-color: #E8EAF0;\n"
"}\n"
"\n"
"QWidget#detailsWidget {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#detailsWidget_2 {\n"
"        background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#detailsWidgetExit {\n"
"        background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QWidget#footerWidget {\n"
"    background-color: #064f32;\n"
"    max-height: 80px;\n"
"}\n"
"\n"
"QWidget#footerWidget_2 {\n"
"    background-color: #064f32;\n"
"    max-height: 80px;\n"
"}\n"
"\n"
"QWidget#footerWidgetExit {\n"
"    background-color: #064f32;\n"
"    max-height: 80px;\n"
"}\n"
"\n"
"QLabel#logoLabel {\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    margin: 0px 20px;\n"
"}\n"
"\n"
"QLabel#logoLabel_2 {\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    margin: 0px 20px;\n"
"}\n"
"\n"
"QLabel#logoLabelExit {\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    margin: 0px 20px;\n"
"}\n"
"\n"
"\n"
"QLabel#schoolNameLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    max-width: 500px;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolNameLabel_2 {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    max-width: 500px;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"QLabel#schoolNameLabelExit {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 30px;\n"
"    max-width: 500px;\n"
"    qproperty-alignment: AlignBottom;\n"
"}\n"
"\n"
"\n"
"QLabel#schoolSubLabel {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#schoolSubLabel_2 {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#schoolSubLabelExit {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QLabel#dateTimeLabel_2 {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QLabel#dateTimeLabelExit {\n"
"    color: #fff;\n"
"    font-size: 20px;\n"
"    margin-right: 20px;\n"
"}\n"
"\n"
"QLabel#footerLabel {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel#footerLabel_2 {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel#footerLabelExit {\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    width: 100%;\n"
"}\n"
"\n"
"QLabel#nameLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#entryLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#idLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#programLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#statusLabel {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#statusLabelExit {\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QLabel#cameraFeed {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel#cameraFeed_2 {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel#cameraFeedExit {\n"
"    background-color: #fff;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"\n"
"QPushButton#btnFace,\n"
"QPushButton#btnFinger {\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: #ffffff;\n"
"    color: #4CAF50;\n"
"    padding: 8px 18px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"/* left button rounded */\n"
"QPushButton#btnFace {\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"/* right button rounded */\n"
"QPushButton#btnFinger {\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"/* hover (unselected) */\n"
"QPushButton#btnFace:hover,\n"
"QPushButton#btnFinger:hover {\n"
"    background-color: #E6F5E8;\n"
"}\n"
"\n"
"/* pressed */\n"
"QPushButton#btnFace:pressed,\n"
"QPushButton#btnFinger:pressed {\n"
"    background-color: #D3EDD7;\n"
"}\n"
"\n"
"/* CHECKED — show selected */\n"
"QPushButton#btnFace:checked,\n"
"QPushButton#btnFinger:checked {\n"
"    background-color: #4CAF50;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* hover while selected */\n"
"QPushButton#btnFace:checked:hover,\n"
"QPushButton#btnFinger:checked:hover {\n"
"    background-color: #43A047;\n"
"}\n"
"\n"
"QPushButton#btnSubmit {\n"
"    border-radius: 12px;\n"
"    border: none;\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    qproperty-iconSize: 20px;\n"
"}\n"
"\n"
"QPushButton#btnSubmit:hover {\n"
"    background-color: #43A047; \n"
"}\n"
"\n"
"QPushButton#btnSubmit:pressed {\n"
"    background-color: #3C8F3F;\n"
"}\n"
"\n"
"QLineEdit#txtStudentNo {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: #f9f9f9;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    border-radius: 10px;\n"
"    padding: 20px 30px;\n"
"    background-color: #eee;\n"
"    color: #333;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Default button style in toolbar */\n"
"\n"
"QToolBar{\n"
"    background: white;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background: transparent;\n"
"    padding: 5px 10px;\n"
"    margin: 2px 6px;\n"
"    border-radius: 8px;\n"
"    min-width: 100px;\n"
"    color: #333;\n"
"}\n"
"\n"
"/* Hover */\n"
"QToolBar QToolButton:hover {\n"
"    background: #1c855a;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Pressed */\n"
"QToolBar QToolButton:pressed {\n"
"    background: #064f32;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Checked (active tab) */\n"
"QToolBar QToolButton:checked {\n"
"    background: #064f32;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Citadel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_main)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.titleWidget = QtWidgets.QWidget(parent=self.page_main)
        self.titleWidget.setEnabled(True)
        self.titleWidget.setMinimumSize(QtCore.QSize(1280, 100))
        self.titleWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(120, 50))
        self.logoLabel.setMaximumSize(QtCore.QSize(120, 80))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.titleLayout.addWidget(self.logoLabel)
        self.engLogoLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.engLogoLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.engLogoLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.engLogoLabel.setText("")
        self.engLogoLabel.setPixmap(QtGui.QPixmap("gui/assets/Engineering_Logo.ico"))
        self.engLogoLabel.setScaledContents(True)
        self.engLogoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engLogoLabel.setObjectName("engLogoLabel")
        self.titleLayout.addWidget(self.engLogoLabel)
        self.logoSpacer = QtWidgets.QLabel(parent=self.titleWidget)
        self.logoSpacer.setMinimumSize(QtCore.QSize(20, 0))
        self.logoSpacer.setMaximumSize(QtCore.QSize(20, 16777215))
        self.logoSpacer.setText("")
        self.logoSpacer.setObjectName("logoSpacer")
        self.titleLayout.addWidget(self.logoSpacer)
        self.schoolLayout = QtWidgets.QVBoxLayout()
        self.schoolLayout.setObjectName("schoolLayout")
        self.schoolNameLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.schoolNameLabel.setScaledContents(True)
        self.schoolNameLabel.setObjectName("schoolNameLabel")
        self.schoolLayout.addWidget(self.schoolNameLabel)
        self.schoolSubLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.schoolSubLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.schoolSubLabel.setObjectName("schoolSubLabel")
        self.schoolLayout.addWidget(self.schoolSubLabel)
        self.titleLayout.addLayout(self.schoolLayout)
        self.dateTimeLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.dateTimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.titleLayout.addWidget(self.dateTimeLabel)
        self.onlineLabel = QtWidgets.QLabel(parent=self.titleWidget)
        self.onlineLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.onlineLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.onlineLabel.setText("")
        self.onlineLabel.setObjectName("onlineLabel")
        self.titleLayout.addWidget(self.onlineLabel)
        self.horizontalLayout1.addLayout(self.titleLayout)
        self.mainLayout.addWidget(self.titleWidget)
        self.bodyWidget = QtWidgets.QWidget(parent=self.page_main)
        self.bodyWidget.setEnabled(True)
        self.bodyWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.bodyWidget.setAutoFillBackground(False)
        self.bodyWidget.setObjectName("bodyWidget")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.bodyWidget)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.bodyLayout = QtWidgets.QHBoxLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.cameraLayout = QtWidgets.QHBoxLayout()
        self.cameraLayout.setContentsMargins(-1, 22, -1, 22)
        self.cameraLayout.setObjectName("cameraLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout.addItem(spacerItem)
        self.cameraFeed = QtWidgets.QLabel(parent=self.bodyWidget)
        self.cameraFeed.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraFeed.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.cameraFeed.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraFeed.setText("")
        self.cameraFeed.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.cameraFeed.setScaledContents(False)
        self.cameraFeed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraFeed.setObjectName("cameraFeed")
        self.cameraLayout.addWidget(self.cameraFeed)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayout.addItem(spacerItem1)
        self.bodyLayout.addLayout(self.cameraLayout)
        self.detailsContainer = QtWidgets.QWidget(parent=self.bodyWidget)
        self.detailsContainer.setObjectName("detailsContainer")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.detailsContainer)
        self.horizontalLayout3.setContentsMargins(-1, 22, -1, 22)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3.addItem(spacerItem2)
        self.detailsWidget = QtWidgets.QWidget(parent=self.detailsContainer)
        self.detailsWidget.setObjectName("detailsWidget")
        self.verticalLayout3 = QtWidgets.QVBoxLayout(self.detailsWidget)
        self.verticalLayout3.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout3.setSpacing(10)
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.detailsLayout = QtWidgets.QVBoxLayout()
        self.detailsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.detailsLayout.setContentsMargins(50, 50, 50, 0)
        self.detailsLayout.setSpacing(15)
        self.detailsLayout.setObjectName("detailsLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.detailsWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.detailsLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.detailsWidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.detailsLayout.addWidget(self.label_4)
        self.nameLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(16)
        font.setBold(False)
        self.nameLabel.setFont(font)
        self.nameLabel.setAutoFillBackground(False)
        self.nameLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.nameLabel.setScaledContents(True)
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLabel.setWordWrap(True)
        self.nameLabel.setObjectName("nameLabel")
        self.detailsLayout.addWidget(self.nameLabel)
        self.idLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        self.idLabel.setFont(font)
        self.idLabel.setAutoFillBackground(False)
        self.idLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.idLabel.setScaledContents(True)
        self.idLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.idLabel.setWordWrap(True)
        self.idLabel.setObjectName("idLabel")
        self.detailsLayout.addWidget(self.idLabel)
        self.programLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        self.programLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        self.programLabel.setFont(font)
        self.programLabel.setAutoFillBackground(False)
        self.programLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.programLabel.setScaledContents(True)
        self.programLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.programLabel.setWordWrap(True)
        self.programLabel.setObjectName("programLabel")
        self.detailsLayout.addWidget(self.programLabel)
        self.yearSecLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.yearSecLabel.setFont(font)
        self.yearSecLabel.setScaledContents(True)
        self.yearSecLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yearSecLabel.setWordWrap(True)
        self.yearSecLabel.setObjectName("yearSecLabel")
        self.detailsLayout.addWidget(self.yearSecLabel)
        self.entryLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.entryLabel.setFont(font)
        self.entryLabel.setAutoFillBackground(False)
        self.entryLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.entryLabel.setScaledContents(True)
        self.entryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.entryLabel.setWordWrap(True)
        self.entryLabel.setObjectName("entryLabel")
        self.detailsLayout.addWidget(self.entryLabel)
        self.spacerLabel = QtWidgets.QLabel(parent=self.detailsWidget)
        self.spacerLabel.setText("")
        self.spacerLabel.setObjectName("spacerLabel")
        self.detailsLayout.addWidget(self.spacerLabel)
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setContentsMargins(125, 10, 125, 10)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.statusWidget = QtWidgets.QWidget(parent=self.detailsWidget)
        self.statusWidget.setMinimumSize(QtCore.QSize(100, 50))
        self.statusWidget.setObjectName("statusWidget")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.statusWidget)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.statusLabel = QtWidgets.QLabel(parent=self.statusWidget)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.statusLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setAutoFillBackground(False)
        self.statusLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.statusLabel.setText("")
        self.statusLabel.setScaledContents(True)
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout5.addWidget(self.statusLabel)
        self.horizontalLayout4.addWidget(self.statusWidget)
        self.detailsLayout.addLayout(self.horizontalLayout4)
        self.label = QtWidgets.QLabel(parent=self.detailsWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.detailsLayout.addWidget(self.label)
        self.verticalLayout3.addLayout(self.detailsLayout)
        self.horizontalLayout3.addWidget(self.detailsWidget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3.addItem(spacerItem3)
        self.bodyLayout.addWidget(self.detailsContainer)
        self.horizontalLayout2.addLayout(self.bodyLayout)
        self.mainLayout.addWidget(self.bodyWidget)
        self.footerWidget = QtWidgets.QWidget(parent=self.page_main)
        self.footerWidget.setMinimumSize(QtCore.QSize(1280, 70))
        self.footerWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.footerWidget.setObjectName("footerWidget")
        self.footerHBox = QtWidgets.QHBoxLayout(self.footerWidget)
        self.footerHBox.setObjectName("footerHBox")
        self.footerLabel = QtWidgets.QLabel(parent=self.footerWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(10)
        font.setBold(True)
        self.footerLabel.setFont(font)
        self.footerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.footerLabel.setWordWrap(False)
        self.footerLabel.setObjectName("footerLabel")
        self.footerHBox.addWidget(self.footerLabel)
        self.mainLayout.addWidget(self.footerWidget)
        self.gridLayout_3.addLayout(self.mainLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_main)
        self.page_exit = QtWidgets.QWidget()
        self.page_exit.setObjectName("page_exit")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_exit)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.titleWidgetExit = QtWidgets.QWidget(parent=self.page_exit)
        self.titleWidgetExit.setEnabled(True)
        self.titleWidgetExit.setMinimumSize(QtCore.QSize(1280, 100))
        self.titleWidgetExit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleWidgetExit.setObjectName("titleWidgetExit")
        self.horizontalLayout1_3 = QtWidgets.QHBoxLayout(self.titleWidgetExit)
        self.horizontalLayout1_3.setObjectName("horizontalLayout1_3")
        self.titleLayoutExit = QtWidgets.QHBoxLayout()
        self.titleLayoutExit.setObjectName("titleLayoutExit")
        self.logoLabelExit = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.logoLabelExit.setMinimumSize(QtCore.QSize(120, 50))
        self.logoLabelExit.setMaximumSize(QtCore.QSize(120, 80))
        self.logoLabelExit.setText("")
        self.logoLabelExit.setPixmap(QtGui.QPixmap("gui/assets/UCC_Logo.ico"))
        self.logoLabelExit.setScaledContents(True)
        self.logoLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabelExit.setObjectName("logoLabelExit")
        self.titleLayoutExit.addWidget(self.logoLabelExit)
        self.engLogoLabelExit = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.engLogoLabelExit.setMinimumSize(QtCore.QSize(80, 80))
        self.engLogoLabelExit.setMaximumSize(QtCore.QSize(80, 80))
        self.engLogoLabelExit.setText("")
        self.engLogoLabelExit.setPixmap(QtGui.QPixmap("gui/assets/Engineering_Logo.ico"))
        self.engLogoLabelExit.setScaledContents(True)
        self.engLogoLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engLogoLabelExit.setObjectName("engLogoLabelExit")
        self.titleLayoutExit.addWidget(self.engLogoLabelExit)
        self.logoSpacer_3 = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.logoSpacer_3.setMinimumSize(QtCore.QSize(20, 0))
        self.logoSpacer_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.logoSpacer_3.setText("")
        self.logoSpacer_3.setObjectName("logoSpacer_3")
        self.titleLayoutExit.addWidget(self.logoSpacer_3)
        self.schoolLayoutExit = QtWidgets.QVBoxLayout()
        self.schoolLayoutExit.setObjectName("schoolLayoutExit")
        self.schoolNameLabelExit = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.schoolNameLabelExit.setScaledContents(True)
        self.schoolNameLabelExit.setObjectName("schoolNameLabelExit")
        self.schoolLayoutExit.addWidget(self.schoolNameLabelExit)
        self.schoolSubLabelExit = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.schoolSubLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.schoolSubLabelExit.setObjectName("schoolSubLabelExit")
        self.schoolLayoutExit.addWidget(self.schoolSubLabelExit)
        self.titleLayoutExit.addLayout(self.schoolLayoutExit)
        self.dateTimeLabelExit = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.dateTimeLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeLabelExit.setObjectName("dateTimeLabelExit")
        self.titleLayoutExit.addWidget(self.dateTimeLabelExit)
        self.onlineLabel_2 = QtWidgets.QLabel(parent=self.titleWidgetExit)
        self.onlineLabel_2.setMinimumSize(QtCore.QSize(80, 80))
        self.onlineLabel_2.setMaximumSize(QtCore.QSize(80, 80))
        self.onlineLabel_2.setText("")
        self.onlineLabel_2.setObjectName("onlineLabel_2")
        self.titleLayoutExit.addWidget(self.onlineLabel_2)
        self.horizontalLayout1_3.addLayout(self.titleLayoutExit)
        self.gridLayout.addWidget(self.titleWidgetExit, 0, 0, 1, 1)
        self.bodyWidgetExit = QtWidgets.QWidget(parent=self.page_exit)
        self.bodyWidgetExit.setEnabled(True)
        self.bodyWidgetExit.setMinimumSize(QtCore.QSize(0, 0))
        self.bodyWidgetExit.setAutoFillBackground(False)
        self.bodyWidgetExit.setObjectName("bodyWidgetExit")
        self.horizontalLayout2_2 = QtWidgets.QHBoxLayout(self.bodyWidgetExit)
        self.horizontalLayout2_2.setObjectName("horizontalLayout2_2")
        self.bodyLayoutExit = QtWidgets.QHBoxLayout()
        self.bodyLayoutExit.setObjectName("bodyLayoutExit")
        self.cameraLayoutExit = QtWidgets.QHBoxLayout()
        self.cameraLayoutExit.setContentsMargins(-1, 22, -1, 22)
        self.cameraLayoutExit.setObjectName("cameraLayoutExit")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayoutExit.addItem(spacerItem4)
        self.cameraFeedExit = QtWidgets.QLabel(parent=self.bodyWidgetExit)
        self.cameraFeedExit.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraFeedExit.setMaximumSize(QtCore.QSize(16662777, 16662777))
        self.cameraFeedExit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraFeedExit.setText("")
        self.cameraFeedExit.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.cameraFeedExit.setScaledContents(False)
        self.cameraFeedExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraFeedExit.setObjectName("cameraFeedExit")
        self.cameraLayoutExit.addWidget(self.cameraFeedExit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cameraLayoutExit.addItem(spacerItem5)
        self.bodyLayoutExit.addLayout(self.cameraLayoutExit)
        self.detailsContainerExit = QtWidgets.QWidget(parent=self.bodyWidgetExit)
        self.detailsContainerExit.setObjectName("detailsContainerExit")
        self.horizontalLayout3_3 = QtWidgets.QHBoxLayout(self.detailsContainerExit)
        self.horizontalLayout3_3.setContentsMargins(-1, 22, -1, 22)
        self.horizontalLayout3_3.setObjectName("horizontalLayout3_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3_3.addItem(spacerItem6)
        self.detailsWidgetExit = QtWidgets.QWidget(parent=self.detailsContainerExit)
        self.detailsWidgetExit.setObjectName("detailsWidgetExit")
        self.verticalLayout3_2 = QtWidgets.QVBoxLayout(self.detailsWidgetExit)
        self.verticalLayout3_2.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout3_2.setSpacing(10)
        self.verticalLayout3_2.setObjectName("verticalLayout3_2")
        self.detailsLayoutExit = QtWidgets.QVBoxLayout()
        self.detailsLayoutExit.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.detailsLayoutExit.setContentsMargins(50, 50, 50, 0)
        self.detailsLayoutExit.setSpacing(15)
        self.detailsLayoutExit.setObjectName("detailsLayoutExit")
        self.label_3 = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.detailsLayoutExit.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.detailsLayoutExit.addWidget(self.label_5)
        self.nameLabelExit = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        self.nameLabelExit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(16)
        font.setBold(False)
        self.nameLabelExit.setFont(font)
        self.nameLabelExit.setAutoFillBackground(False)
        self.nameLabelExit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.nameLabelExit.setScaledContents(True)
        self.nameLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLabelExit.setWordWrap(True)
        self.nameLabelExit.setObjectName("nameLabelExit")
        self.detailsLayoutExit.addWidget(self.nameLabelExit)
        self.idLabelExit = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        self.idLabelExit.setFont(font)
        self.idLabelExit.setAutoFillBackground(False)
        self.idLabelExit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.idLabelExit.setScaledContents(True)
        self.idLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.idLabelExit.setWordWrap(True)
        self.idLabelExit.setObjectName("idLabelExit")
        self.detailsLayoutExit.addWidget(self.idLabelExit)
        self.programLabelExit = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        self.programLabelExit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(14)
        self.programLabelExit.setFont(font)
        self.programLabelExit.setAutoFillBackground(False)
        self.programLabelExit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.programLabelExit.setScaledContents(True)
        self.programLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.programLabelExit.setWordWrap(True)
        self.programLabelExit.setObjectName("programLabelExit")
        self.detailsLayoutExit.addWidget(self.programLabelExit)
        self.yearSecLabelExit = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.yearSecLabelExit.setFont(font)
        self.yearSecLabelExit.setScaledContents(True)
        self.yearSecLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yearSecLabelExit.setWordWrap(True)
        self.yearSecLabelExit.setObjectName("yearSecLabelExit")
        self.detailsLayoutExit.addWidget(self.yearSecLabelExit)
        self.entryLabelExit = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.entryLabelExit.setFont(font)
        self.entryLabelExit.setAutoFillBackground(False)
        self.entryLabelExit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.entryLabelExit.setScaledContents(True)
        self.entryLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.entryLabelExit.setWordWrap(True)
        self.entryLabelExit.setObjectName("entryLabelExit")
        self.detailsLayoutExit.addWidget(self.entryLabelExit)
        self.spacerLabel_2 = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        self.spacerLabel_2.setText("")
        self.spacerLabel_2.setObjectName("spacerLabel_2")
        self.detailsLayoutExit.addWidget(self.spacerLabel_2)
        self.horizontalLayout4_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4_2.setContentsMargins(125, 10, 125, 10)
        self.horizontalLayout4_2.setObjectName("horizontalLayout4_2")
        self.statusWidgetExit = QtWidgets.QWidget(parent=self.detailsWidgetExit)
        self.statusWidgetExit.setMinimumSize(QtCore.QSize(100, 50))
        self.statusWidgetExit.setObjectName("statusWidgetExit")
        self.horizontalLayout5_3 = QtWidgets.QHBoxLayout(self.statusWidgetExit)
        self.horizontalLayout5_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5_3.setObjectName("horizontalLayout5_3")
        self.statusLabelExit = QtWidgets.QLabel(parent=self.statusWidgetExit)
        self.statusLabelExit.setMinimumSize(QtCore.QSize(0, 0))
        self.statusLabelExit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(12)
        self.statusLabelExit.setFont(font)
        self.statusLabelExit.setAutoFillBackground(False)
        self.statusLabelExit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.statusLabelExit.setText("")
        self.statusLabelExit.setScaledContents(True)
        self.statusLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabelExit.setWordWrap(True)
        self.statusLabelExit.setObjectName("statusLabelExit")
        self.horizontalLayout5_3.addWidget(self.statusLabelExit)
        self.horizontalLayout4_2.addWidget(self.statusWidgetExit)
        self.detailsLayoutExit.addLayout(self.horizontalLayout4_2)
        self.spacerLabel_3 = QtWidgets.QLabel(parent=self.detailsWidgetExit)
        self.spacerLabel_3.setText("")
        self.spacerLabel_3.setObjectName("spacerLabel_3")
        self.detailsLayoutExit.addWidget(self.spacerLabel_3)
        self.verticalLayout3_2.addLayout(self.detailsLayoutExit)
        self.horizontalLayout3_3.addWidget(self.detailsWidgetExit)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout3_3.addItem(spacerItem7)
        self.bodyLayoutExit.addWidget(self.detailsContainerExit)
        self.horizontalLayout2_2.addLayout(self.bodyLayoutExit)
        self.gridLayout.addWidget(self.bodyWidgetExit, 1, 0, 1, 1)
        self.footerWidgetExit = QtWidgets.QWidget(parent=self.page_exit)
        self.footerWidgetExit.setMinimumSize(QtCore.QSize(1280, 70))
        self.footerWidgetExit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.footerWidgetExit.setObjectName("footerWidgetExit")
        self.footerHBox_3 = QtWidgets.QHBoxLayout(self.footerWidgetExit)
        self.footerHBox_3.setObjectName("footerHBox_3")
        self.footerLabelExit = QtWidgets.QLabel(parent=self.footerWidgetExit)
        font = QtGui.QFont()
        font.setFamily("Poppins-Regular")
        font.setPointSize(10)
        font.setBold(True)
        self.footerLabelExit.setFont(font)
        self.footerLabelExit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.footerLabelExit.setWordWrap(False)
        self.footerLabelExit.setObjectName("footerLabelExit")
        self.footerHBox_3.addWidget(self.footerLabelExit)
        self.gridLayout.addWidget(self.footerWidgetExit, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_exit)
        self.verticalLayout1.addWidget(self.stackedWidget)
        Citadel.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(parent=Citadel)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolBar.setObjectName("toolBar")
        Citadel.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.retranslateUi(Citadel)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Citadel)

    def retranslateUi(self, Citadel):
        _translate = QtCore.QCoreApplication.translate
        Citadel.setWindowTitle(_translate("Citadel", "Citadel"))
        self.schoolNameLabel.setText(_translate("Citadel", "University of Caloocan City"))
        self.schoolSubLabel.setText(_translate("Citadel", "Bagong Silang Campus | College of Engineering"))
        self.dateTimeLabel.setText(_translate("Citadel", "October 15, 2025 | 05:00AM"))
        self.label_2.setText(_translate("Citadel", "STUDENT DATA"))
        self.nameLabel.setText(_translate("Citadel", "Name"))
        self.idLabel.setText(_translate("Citadel", "ID"))
        self.programLabel.setText(_translate("Citadel", "Program"))
        self.yearSecLabel.setText(_translate("Citadel", "Year and Section"))
        self.entryLabel.setText(_translate("Citadel", "Time"))
        self.footerLabel.setText(_translate("Citadel", "Welcome to University of Caloocan City | Please scan your QR code and verify through biometrics for secure access."))
        self.schoolNameLabelExit.setText(_translate("Citadel", "University of Caloocan City"))
        self.schoolSubLabelExit.setText(_translate("Citadel", "Bagong Silang Campus | College of Engineering"))
        self.dateTimeLabelExit.setText(_translate("Citadel", "October 15, 2025 | 05:00AM"))
        self.label_3.setText(_translate("Citadel", "STUDENT DATA"))
        self.nameLabelExit.setText(_translate("Citadel", "Name"))
        self.idLabelExit.setText(_translate("Citadel", "ID"))
        self.programLabelExit.setText(_translate("Citadel", "Program"))
        self.yearSecLabelExit.setText(_translate("Citadel", "Year and Section"))
        self.entryLabelExit.setText(_translate("Citadel", "Time"))
        self.footerLabelExit.setText(_translate("Citadel", "Welcome to University of Caloocan City | Please scan your QR code and verify through biometrics for secure access."))
        self.toolBar.setWindowTitle(_translate("Citadel", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Citadel = QtWidgets.QMainWindow()
    ui = Ui_Citadel()
    ui.setupUi(Citadel)
    Citadel.show()
    sys.exit(app.exec())
